name: Feature Request
description: Please enter the details of the feature you want added
body:
  - type: input
    attributes:
      label: What would you like to be added?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Why?
      description: Explain why you want this to be added
    validations:
      required: true

  - type: textarea
    attributes:
      label: Examples
      description: Add any examples (photos, videos, etc.) of your feature from other places
